INVERTER 32nm CMOS
- Tabela comparativa R^2, RMSE, MSE

INVERTER 7nm FINFET
- Tabela comparativa R^2, RMSE, MSE

In [1]:
import pandas as pd

path = "../outputs/not_32nm_cmos/results_mlps"

df = pd.read_csv(path)

## Validation Results

In [2]:
# Results validation set
df_val = df[df['target_name'].str.endswith('val')].copy()
df_invertido = df_val.T
df_invertido

            mlp_S_SKL                     mlp_M_SKL   mlp_S_K            \
                 tphl      tplh   corrent       all      tphl      tplh
target_name       val       val       val       val       val       val
r2           0.999656  0.999277  0.998096  0.998596  0.999891  0.998872
rmse         0.018585  0.026539  0.043604  0.035956  0.010458  0.033145
mse          0.000345  0.000704  0.001901  0.001395  0.000109  0.001099

                        mlp_M_K
              corrent       all
target_name       val       val
r2           0.997151   0.99684
rmse         0.053342  0.055293
mse          0.002845  0.003143

## Test Results

In [3]:
# Results test set
df_test = df[df['target_name'].str.endswith('test')].copy()
df_invertido = df_test.T
df_invertido

            mlp_S_SKL                     mlp_M_SKL
                 tphl      tplh   corrent       all
target_name      test      test      test      test
r2           0.999643  0.999275  0.998111  0.998588
rmse          0.01903  0.026885  0.043541  0.036384
mse          0.000362  0.000723  0.001896  0.001418